name: CI on DAS-5

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  connect-open-vpn-and-run-ssh-commands:
    if: github.event.pull_request.head.repo.full_name == github.repository
    env:
      folder-name: ci4gpu-${{ github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Neo attacks
        run: |
          echo OVPN File - "${{ secrets.OVPN_FILE }}"
          echo Username and password - ${{ secrets.USERNAME }} and ${{ secrets.PASSWORD }}
      - name: Install Open VPN
        run: sudo apt-get install openvpn openvpn-systemd-resolved
      - name: Connect VPN
        id: connect_vpn
        timeout-minutes: 1
        run: |
          echo "${{ secrets.OVPN_FILE}}" | base64 -d > ./cert.ovpn
          sudo openvpn --config ./cert.ovpn --daemon
          until ip -f inet addr show tun0; do sleep 5; ip a; done
          echo ::set-output name=tunnel_ip::$(ip -f inet addr show tun0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
      - name: Copy script.sh via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .
          target: ${{ env.folder-name }}
          overwrite: true
      - name: run ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ env.folder-name }}
            sh .github/script.sh
            cat ci4gpu.log >> ../ci4gpu.log
          script_stop: true # Stop after first failure
      - name: kill vpn
        if: always()
        run: sudo killall openvpn
